version: '3.8'

services:
  aop:
    build:
      context: .
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: t1_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t1school
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: