version: '3.8'

services:
  supplier:
    build:
      context: ./SupplierService
    ports:
      - "8080:8080"

  consumer:
    build:
      context: ./ConsumerService
    ports:
      - "8081:8081"

  postgres:
    image: postgres:latest
    container_name: t1_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t1school
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: